### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by ngoohebi** [eggheadgames/android-realm-asset-helper#6]
Some device crashed when loading the database during application onCreate.
Any idea?

`Fatal Exception: java.lang.OutOfMemoryError
       at com.eggheadgames.realmassethelper.OsUtil.loadDatabaseToLocalStorage(Unknown Source)
       at com.eggheadgames.realmassethelper.RealmAssetHelper.getInstance(Unknown Source)
       at com.myapp.MyAppApplication.onCreate(Unknown Source)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4218)
       at android.app.ActivityThread.access$1300(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1275)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4812)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by mikemee** [comment]
@shiami Sorry for not responding sooner(!).  I don't know of a reason why this might have happened. Did you work it out?  Was the database particularly large?

I'm closing this issue as part of a general refresh, but if you did have more information to add, perhaps it could help someone else.

Thanks, Michael

**Comment by ngoohebi** [comment]
@mikemee 

Please check my fork. I did some modifications.
https://github.com/eggheadgames/android-realm-asset-helper/compare/master...shiami:master

**Comment by mikemee** [comment]
@shiami Fantastic, thanks!  I notice you dropped it from 10k to 1k. Were you still getting errors at 10k, or perhaps this was a conservative value just in case?

Re-opening so we can make this same change to the library.

**Comment by mikemee** [comment]
@shiami Also, I wonder if it should be `min(is.available(), 1024)` rather than 1024?  (Maybe that's why 10240 had problems. Any thoughts on that?

Thanks again!

**Comment by AlexDibrivnyy** [comment]
I would like to share my point of view. 
Previously it crashed because we get a file from asset and fully put it to the memory buffer. Memory heap on the old devices was very small and let's imagine that file is big and we do not have a free space for it. As a result, it will crash. This you can see here:
```
            InputStream is = context.getAssets().open(asset);
            int size = is.available();
            byte[] buffer = new byte[size];
            is.read(buffer);
```

The new version makes it much more efficient. It creates a buffer of 1024 and copies the file partially.

```
 Were you still getting errors at 10k, or perhaps this was a conservative value just in case?
```

10k is a big number, we need to use smaller chunks to be sure that we always have free memory for this process.


```
Also, I wonder if it should be min(is.available(), 1024) rather than 1024? (Maybe that's why 10240 had problems. Any thoughts on that?
```

This is a possible variant, but all realm files that I checked were more than 1024. Even if the file will be less, then this case is covered by the 'length' field.

```
   while ((length = is.read(buffer)) >= 0) {
                fos.write(buffer, 0, length);
   } 

```
